services:
  web:
    build: .
    container_name: reflect_uv_app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=dev
